### PR TITLE
Enable building universal wheels

### PR DESCRIPTION
**Pull request by dhellmann**
Remove the use of execfile() in setup.py so it can run under python 3.

Set the flag in setup.cfg to allow universal wheels.

### CODE REVIEW

**Comment by dhellmann** [comment]
Without this change in place, I see this error:

  $ python setup.py bdist_wheel
  Traceback (most recent call last):
    File "setup.py", line 5, in <module>
      execfile('happybase/_version.py')
  NameError: name 'execfile' is not defined

**Comment by wbolster** [comment]
Thanks!

FYI, Happybase only supported Python 2 because the Thrift library it depends on lacked Python 3 support. It seems that is now a thing of the past.

**Comment by dhellmann** [comment]
I wasn't actually able to build wheels at all without the changes to setup.py. The "universal" flag was added as a "bonus".

**Comment by wbolster** [comment]
I don't understand. Why would `execfile` fail? In Python 3 that function doesn't exist anymore, but in Python 2 it should be there, right?

**Comment by dhellmann** [comment]
Ah, my default pip happens to be configured to point to python3, so if I run "pip wheel happybase" it fails.

**Comment by wbolster** [comment]
Okay, I will merge this when I find time to get the other stuff required to release a version with Python 3 support done (#40).

**Pull request merged**
