### PR TITLE
Added host failover

### PR DESCRIPTION
**Pull request by Arttii**
Added a basic mechanism for host failover. You just need to supply a list of other hosts to try. Its a simple solution, but seems to work ok.

### CODE REVIEW

**Comment by wbolster** [comment]
I think this is not worth the complexity in HappyBase, since it's a complex problem that isn't solved properly using a simple `for` loop. See e.g. https://github.com/wbolster/happybase/issues/21#issuecomment-16885173 for discussion.

(Furthermore, your code has typos in variable names so I doubt it's actually tested...)

**Comment by Arttii** [comment]
I do not see what you mean by complexity. This is a very simple solution to the problem. Not the best one, but it works, which is a nicer alternative to having you jobs just fail if the on Thriftserver is dead. Also I dont know what typos you referring to. This code is currently running in multiple jobs.

**Comment by wbolster** [comment]
There's a few things to note here:

* This PR treats one host as the "preferred" host, and uses the others only as a fallback. This is not a good approach to fail-over or load-balancing. In short, simple fail-over to backup hosts in `Connection.open()` doesn't properly solve any high availability or load balancing problems. Dedicated solutions such as haproxy do. See the comment and discussion referenced earlier. Maybe @chase-seibert can chime in here and explain?
* Happybase is only a consumer of the Thrift API and its exceptions; it shouldn't raise exceptions "owned" by other libraries (which this PR does), i.e. it touches another's "private parts".

Re. the typos: `falis+=1` is a code path that clearly has never been executed.

**Comment by wbolster** [comment]
Also, the functionality as proposed in this PR can also be implemented _outside_ of Happybase by simply creating a function that wraps `Connection.open()`.

**Comment by Arttii** [comment]
Yes I understand now, there was not a lot of information on this topics. I looked into HAProxy and I am probably migrating our solution to that now. Thanks for the clarification.

**Comment by wbolster** [comment]
Sorry @Arttii can't help you; no experience. But perhaps @chase-seibert can join the discussion?

**Comment by chase-seibert** [comment]
I would just echo again that an external load balancer is a more complete solution to the same problem. Not only do you get fail-over, but you can also distribute load evenly between two hot hosts, versus having one hot and one passive. 

Even if you tried to do that in code, you would run into the problem of some hosts maintaining long-lived connections to a particular server. Other hosts would not be able to take that information into account to implement a truly least-connection load balancing scheme.

**Comment by Arttii** [comment]
Yes thank you, I realize now I was kinda missing the point with my solution. I implemented the failover with HAProxy now. Works quite well, thanks for the insight.
________________________________

**Pull request closed without merging**
