### PR TITLE
Python 3 Compatibility

### PR DESCRIPTION
**Pull request by surfacepatterns**
Even though I'm making a pull request, it's probably not reasonable to accept the pull request *yet*.  I say this because:

1. The thrift compiler generated incorrect Python 3 bindings up until eight weeks ago, when [this commit](https://git-wip-us.apache.org/repos/asf?p=thrift.git;a=commit;h=4fcc74478ff62da677215eddcbaacacab76c7e41) was made.  The commit made it so that absolute imports weren't used to import submodules in generated bindings.
2. Bindings generated by code in the thrift master branch reference classes that are not necessarily available in earlier versions of python thrift bindings.

In consequence, I'd probably wait for a new release of Thrift before accepting the pull request.

Aside from that, I should say a few things about my changes:

1. The Hbase.thrift file indicates the bindings should accept unicode arguments in types marked as 'Text', but generated python bindings accept bytes objects.  I decided that the happybase API should still do the right thing in those cases; hence, str.encode() and bytes.decode() are used pretty liberally.  
2. Some functions that normally return an iterator in Python 2 aren't available in Python 3 (e.g. xrange(), dict.iteritems(), etc.).  Sometimes, I made the decision to create a convenient alias for Python 3's sake; other times, I chose to use a less efficient method in Python 2.  Feel free to make different choices.
3. I updated the Hbase.thrift file to the newest one in the hbase repository.  I then updated the bindings using the thrift compiler from the current master branch.
4. The happybase test suite was run using both Python 2 and 3.  All tests in the test suite passed in both cases.  I have *not* tested the bindings under any other scenario (yet).

Let me know if you have any questions.

### CODE REVIEW

**Comment by surfacepatterns** [comment]
I've done some reading, and have found that most of the Hbase documentation conflicts with the comment in the Hbase.thrift file that suggests that keys, values, etc. should be UTF-8.  I'm closing this pull request, and will make another pull request which accepts bytes() instances in Python 3.

**Comment by scttcper** [comment]
@surfacepatterns keep it up. Would really like to see python3 support even if it doesn't make it into master.

**Comment by surfacepatterns** [comment]
Created a [new pull request](https://github.com/wbolster/happybase/pull/111) that does the right thing.

**Comment by wbolster** [comment]
yeah data is always bytes and happybase should NOT accept anything else.

helper methods like table names or keys in config dicts are a different story, accepting "native" strings makes sense wherever reasonable.

    — wouter

-- 
sent from my phone. please forgive my tpyos.

**Comment by wbolster** [comment]
it will make it into master. i have a dislike for py2 nowadays 😉

    — wouter

-- 
sent from my phone. please forgive my tpyos.

**Pull request closed without merging**
